### Load Pre-Trained Model and Train, Dev, Test Data


In [1]:
# !pip install sklearn
# !pip install ekphrasis
# !pip install transformers
# !pip install spacy
# !python -m spacy download en_core_web_sm

In [2]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow_datasets as tfds

import transformers

from transformers import BertTokenizer, TFBertModel
from tensorflow.keras import backend as K
from tensorflow import keras

from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

import os

import logging
tf.get_logger().setLevel(logging.ERROR)

In [3]:
train_data_df = pd.read_csv('./EDA_base_uncased_5aug/All_DA_BERT_base_uncased_train_examples.csv')
dev_data_df = pd.read_csv('./EDA_base_uncased_5aug/All_DA_BERT_base_uncased_dev_examples.csv')
test_data_df = pd.read_csv('./EDA_base_uncased_5aug/All_DA_BERT_base_uncased_test_examples.csv')

In [4]:
test_data_df.head()

Unnamed: 0                      post_id  \
0           0  1178851408168263680_twitter   
1           1                  4376210_gab   
2           2  1178735809358450688_twitter   
3           3                 16169240_gab   
4           4                 15983024_gab   

                                                text      target1     target2  \
0  ['empowerment', 'through', 'consumerism', 'is'...     ['None']    ['None']   
1  ['an', 'interesting', 'study', 'could', 'be', ...   ['Jewish']  ['Jewish']   
2  ['there', 'is', 'no', 'logical', 'or', 'just',...     ['None']    ['None']   
3  ['in', '<number>', 'we', 'have', 'to', 'set', ...  ['African']    ['None']   
4  ['ay', 'i', 'am', '<number>', '<number>', 'ita...     ['None']    ['Arab']   

                   target3                                         rationales  \
0                 ['None']                                                 []   
1  ['Caucasian', 'Jewish']  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
2                 ['None']                                                 []   
3                ['Other']                                                 []   
4                 ['Arab']                                                 []   

  final_label                                      text_combined  
0      normal  empowerment through consumerism is fake empowe...  
1  hatespeech  an interesting study could be made of the diff...  
2      normal  there is no logical or just reason for a medio...  
3      normal  in <number> we have to set up video outside th...  
4      normal  ay i am <number> <number> italian bucko i can ...

In [5]:
test_data_text = test_data_df['text_combined'].to_list()
train_data_text = train_data_df['text_combined'].to_list()
dev_data_text = dev_data_df['text_combined'].to_list()

In [6]:
test_data_text

['empowerment through consumerism is fake empowerment ',
 'an interesting study could be made of the difference between jews who are more or less professional leftists and whiteskin leftists particularly in their mentation over time my theory is whiteskins are less able to handle lying as permanent mo than jews ',
 'there is no logical or just reason for a mediocre few shielded from competition propped up by inherited riches and passports to feast on the world riches under the guise of meritocracy <user> ungrateful refugee <number> ',
 'in <number> we have to set up video outside the ghetto polling places so we can count the number of people entering and leaving it literally would not surprise me if almost nobody actually votes in these precincts and it just <number> fraud ',
 'ay i am <number> <number> italian bucko i can make meatballs and stromboli with the best of em but i am blonde and green eyes because the arabs did not invade my part of italy above rome ',
 'we must secure the 

In [7]:
test_data_labels = test_data_df['final_label']
train_data_labels = train_data_df['final_label']
dev_data_labels = dev_data_df['final_label']

In [8]:
def convert_to_oh(S):
    '''takes a pandas series of text labels and returns one hot encoding equivalent
    0 = normal, 1 = offensive, 2 = hatespeech
    ''' 
    S_numerical = S.apply(lambda x: 0 if x=='normal' else (1 if x=='offensive' else 2))
    S_oh = keras.utils.to_categorical(S_numerical, num_classes = 3, dtype = 'float32')
    return S_oh

In [9]:
y_test = convert_to_oh(test_data_labels)
y_train = convert_to_oh(train_data_labels)
y_dev = convert_to_oh(dev_data_labels)

In [10]:
y_test

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

### BERT Model

In [11]:
# tokenize

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
#bert_model = TFBertModel.from_pretrained('bert-base-uncased')

In [12]:
max_length = 128
#x_train = tokenizer(train_data_text , max_length=max_length, truncation=True, padding='max_length', return_tensors='tf')
x_test = tokenizer(test_data_text , max_length=max_length, truncation=True, padding='max_length', return_tensors='tf')
#x_dev = tokenizer(dev_data_text , max_length=max_length, truncation=True, padding='max_length', return_tensors='tf')

In [13]:
x_test

{'input_ids': <tf.Tensor: shape=(1923, 128), dtype=int32, numpy=
array([[  101, 23011,  2083, ...,     0,     0,     0],
       [  101,  2019,  5875, ...,     0,     0,     0],
       [  101,  2045,  2003, ...,     0,     0,     0],
       ...,
       [  101,  2202,  1996, ...,     0,     0,     0],
       [  101,  2070,  1997, ...,     0,     0,     0],
       [  101,  1045,  2572, ...,     0,     0,     0]])>, 'token_type_ids': <tf.Tensor: shape=(1923, 128), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(1923, 128), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])>}

In [14]:
# load selected BERT model

bert_model = TFBertModel.from_pretrained('bert-base-uncased')


Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [15]:
from keras import backend as K

def balanced_recall(y_true, y_pred):
    """This function calculates the balanced recall metric
    recall = TP / (TP + FN)
    """
    recall_by_class = 0
    # iterate over each predicted class to get class-specific metric
    for i in range(y_pred.shape[1]):
        y_pred_class = y_pred[:, i]
        y_true_class = y_true[:, i]
        true_positives = K.sum(K.round(K.clip(y_true_class * y_pred_class, 0, 1)))
        possible_positives = K.sum(K.round(K.clip(y_true_class, 0, 1)))
        recall = true_positives / (possible_positives + K.epsilon())
        recall_by_class = recall_by_class + recall
    return recall_by_class / y_pred.shape[1]

def balanced_precision(y_true, y_pred):
    """This function calculates the balanced precision metric
    precision = TP / (TP + FP)
    """
    precision_by_class = 0
    # iterate over each predicted class to get class-specific metric
    for i in range(y_pred.shape[1]):
        y_pred_class = y_pred[:, i]
        y_true_class = y_true[:, i]
        true_positives = K.sum(K.round(K.clip(y_true_class * y_pred_class, 0, 1)))
        predicted_positives = K.sum(K.round(K.clip(y_pred_class, 0, 1)))
        precision = true_positives / (predicted_positives + K.epsilon())
        precision_by_class = precision_by_class + precision
    # return average balanced metric for each class
    return precision_by_class / y_pred.shape[1]

def balanced_f1_score(y_true, y_pred):
    """This function calculates the F1 score metric"""
    precision = balanced_precision(y_true, y_pred)
    recall = balanced_recall(y_true, y_pred)
    return 2 * ((precision * recall) / (precision + recall + K.epsilon()))

In [16]:
def create_classification_model(bert_model, hidden_size = 5, 
                                train_layers = -1, 
                                optimizer=tf.keras.optimizers.Adam()):
    """
    Build a simple classification model with BERT. Let's keep it simple and don't add dropout, layer norms, etc.
    """

    input_ids = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int32, name='input_ids_layer')
    token_type_ids = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int32, name='token_type_ids_layer')
    attention_mask = tf.keras.layers.Input(shape=(max_length,), dtype=tf.int32, name='attention_mask_layer')

    bert_inputs = {'input_ids': input_ids,
                  'token_type_ids': token_type_ids,
                  'attention_mask': attention_mask}


    #restrict training to the train_layers outer transformer layers
    if not train_layers == -1:

            retrain_layers = []

            for retrain_layer_number in range(train_layers):

                layer_code = '_' + str(11 - retrain_layer_number)
                retrain_layers.append(layer_code)

            for w in bert_model.weights:
                if not any([x in w.name for x in retrain_layers]):
                    w._trainable = False


    bert_out = bert_model(bert_inputs)
    
    net = bert_out[0]
    
    classification_token = tf.keras.layers.Lambda(lambda x: x[:,0,:], name='get_first_vector')(net)
    
    dropout1 = tf.keras.layers.Dropout(0.4, name="dropout1")(classification_token)
    
    hidden = tf.keras.layers.Dense(hidden_size, name='hidden_layer')(dropout1)
    
    dropout2 = tf.keras.layers.Dropout(0.4, name="dropout2")(hidden)

    classification = tf.keras.layers.Dense(3, activation='sigmoid',name='classification_layer')(dropout2)

    classification_model = tf.keras.Model(inputs=[input_ids, token_type_ids, attention_mask], 
                                          outputs=[classification])
    
    METRICS = [tf.keras.metrics.CategoricalAccuracy(name="accuracy"), 
               balanced_recall, 
               balanced_precision, 
               balanced_f1_score,
               tf.keras.metrics.AUC(curve='ROC', name="auc_roc")]
    
    
    classification_model.compile(optimizer=optimizer,
                            loss=tf.keras.losses.CategoricalCrossentropy(),
                            metrics= METRICS)


    return classification_model

In [17]:
# create model

model = create_classification_model(bert_model, hidden_size = 5, train_layers = -1, optimizer=tf.keras.optimizers.Adam())

In [18]:
# load model weights from the fine tuned model you want to look at

# # original data
# model.load_weights('./EDA_base_uncased/original_data_base/original_data_base')

# synonym replacement: sr 0.1
# model.load_weights('./EDA_base_uncased/EDA_sr_base/EDA_sr_base')

# # random insertion: ri 0.1
# model.load_weights('./EDA_base_uncased/EDA_ri_base/EDA_ri_base')

# # random deletion: rd 0.1
# model.load_weights('./EDA_base_uncased/EDA_rd_base/EDA_rd_base')

# # random sway: rs 0.1
# model.load_weights('./EDA_base_uncased/EDA_rs_base/EDA_rs_base')

# # all methods: all 0.1
# model.load_weights('./EDA_base_uncased/EDA_all_1_base/EDA_all_1_base')

# # all methods: all 0.5
# model.load_weights('./EDA_base_uncased/EDA_all_5_base/EDA_all_5_base')

# # contextual insertion
# model.load_weights('./NLA_b_uncased_5aug/NLA_ins_base/NLA_ins_base')

# contextual insertion
model.load_weights('./NLA_b_uncased_5aug/NLA_sub_base/NLA_sub_base')


In [19]:
y_preds_array = model.predict([x_test.input_ids, x_test.token_type_ids, x_test.attention_mask])

In [20]:
# prediction logits

y_preds_array

array([[0.5888786 , 0.5121254 , 0.22753629],
       [0.5395787 , 0.48005375, 0.5323035 ],
       [0.65468377, 0.43723613, 0.2881892 ],
       ...,
       [0.7509989 , 0.28641522, 0.43727416],
       [0.7284408 , 0.38636476, 0.15373392],
       [0.8445087 , 0.27296597, 0.07415991]], dtype=float32)

In [21]:
from keras.utils.np_utils import to_categorical
y_preds = to_categorical(np.argmax(y_preds_array, 1), dtype = "int64")

In [22]:
y_preds

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       ...,
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]], dtype=int64)

In [23]:
# convert back to labels

y_test_cat = np.argmax(y_test, axis=1)
y_preds_cat = np.argmax(y_preds, axis=1)

y_test_cat

array([0, 2, 0, ..., 0, 1, 0], dtype=int64)

In [24]:
y_preds_cat

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [25]:
accuracy_score(y_test_cat, y_preds_cat)

0.7082683307332294

In [26]:
f1_score(y_test_cat, y_preds_cat, average='macro')

0.6819872101827303

In [27]:
roc_auc_score(y_test, y_preds, multi_class='ovo',average='weighted')

0.7753235770592908

In [28]:
test_data_text

['empowerment through consumerism is fake empowerment ',
 'an interesting study could be made of the difference between jews who are more or less professional leftists and whiteskin leftists particularly in their mentation over time my theory is whiteskins are less able to handle lying as permanent mo than jews ',
 'there is no logical or just reason for a mediocre few shielded from competition propped up by inherited riches and passports to feast on the world riches under the guise of meritocracy <user> ungrateful refugee <number> ',
 'in <number> we have to set up video outside the ghetto polling places so we can count the number of people entering and leaving it literally would not surprise me if almost nobody actually votes in these precincts and it just <number> fraud ',
 'ay i am <number> <number> italian bucko i can make meatballs and stromboli with the best of em but i am blonde and green eyes because the arabs did not invade my part of italy above rome ',
 'we must secure the 

In [49]:
test_data_df['text_qc'] = test_data_text
test_data_df['class'] = y_test_cat
test_data_df['pred_class'] = y_preds_cat
test_data_df['correct_pred'] = (test_data_df['class'] == test_data_df['pred_class'])

In [50]:
test_data_df

Unnamed: 0                      post_id  \
0              0  1178851408168263680_twitter   
1              1                  4376210_gab   
2              2  1178735809358450688_twitter   
3              3                 16169240_gab   
4              4                 15983024_gab   
...          ...                          ...   
1918        1918  1120656515143127040_twitter   
1919        1919  1178830600171601924_twitter   
1920        1920  1170506573170561024_twitter   
1921        1921  1178145888922939393_twitter   
1922        1922  1178770890944897024_twitter   

                                                                                                                                                                                                                                                                                                                                                                                              text  \
0                                                                                                                                                                                                                                                                                                                           ['empowerment', 'through', 'consumerism', 'is', 'fake', 'empowerment']   
1     ['an', 'interesting', 'study', 'could', 'be', 'made', 'of', 'the', 'difference', 'between', 'jews', 'who', 'are', 'more', 'or', 'less', 'professional', 'leftists', 'and', 'whiteskin', 'leftists', 'particularly', 'in', 'their', 'mentation', 'over', 'time', 'my', 'theory', 'is', 'whiteskins', 'are', 'less', 'able', 'to', 'handle', 'lying', 'as', 'permanent', 'mo', 'than', 'jews']   
2                                                         ['there', 'is', 'no', 'logical', 'or', 'just', 'reason', 'for', 'a', 'mediocre', 'few', 'shielded', 'from', 'competition', 'propped', 'up', 'by', 'inherited', 'riches', 'and', 'passports', 'to', 'feast', 'on', 'the', 'world', 'riches', 'under', 'the', 'guise', 'of', 'meritocracy', '<user>', 'ungrateful', 'refugee', '<number>']   
3               ['in', '<number>', 'we', 'have', 'to', 'set', 'up', 'video', 'outside', 'the', 'ghetto', 'polling', 'places', 'so', 'we', 'can', 'count', 'the', 'number', 'of', 'people', 'entering', 'and', 'leaving', 'it', 'literally', 'would', 'not', 'surprise', 'me', 'if', 'almost', 'nobody', 'actually', 'votes', 'in', 'these', 'precincts', 'and', 'it', 'just', '<number>', 'fraud']   
4                                                                                       ['ay', 'i', 'am', '<number>', '<number>', 'italian', 'bucko', 'i', 'can', 'make', 'meatballs', 'and', 'stromboli', 'with', 'the', 'best', 'of', 'em', 'but', 'i', 'am', 'blonde', 'and', 'green', 'eyes', 'because', 'the', 'arabs', 'did', 'not', 'invade', 'my', 'part', 'of', 'italy', 'above', 'rome']   
...                                                                                                                                                                                                                                                                                                                                                                                            ...   
1918                                                                                                                                                                                                                                          ['<user>', 'keep', 'muslim', 'away', 'defend', 'christian', 'faith', 'ban', 'abortion', 'welcome', 'black', 'american', 'babies', 'in', 'the', 'us']   
1919                                                                                                                                                                                                                        ['<user>', 'where', 'is', 'the', 'diversity', 'video', 'full', 'of', 'white',

In [54]:
misclass_df = test_data_df[test_data_df['correct_pred'] == False][['post_id', 'target1', 'target2', 'target3', 'text_combined', 'final_label', 'class', 'pred_class', 'correct_pred']]

In [58]:
len(misclass_df)

561

In [55]:
pd.set_option('display.max_colwidth', None)

In [57]:
misclass_df.head()

post_id         target1     target2  \
1                  4376210_gab      ['Jewish']  ['Jewish']   
5  1172328099188330497_twitter        ['None']    ['None']   
6  1278566981466296320_twitter        ['None']   ['Other']   
8                  6070354_gab      ['Jewish']  ['Jewish']   
9  1228700650499784704_twitter  ['Homosexual']    ['None']   

                   target3  \
1  ['Caucasian', 'Jewish']   
5                 ['None']   
6              ['African']   
8               ['Jewish']   
9  ['Homosexual', 'Other']   

                                                                                                                                                                                                                                                    text_combined  \
1  an interesting study could be made of the difference between jews who are more or less professional leftists and whiteskin leftists particularly in their mentation over time my theory is whiteskins are less able to handle lying as permanent mo than jews    
5                                                                                                                                                                                   we must secure the existence of vape pens and a future for white vape clouds    
6                                                                                                                                                         i don ’ t see how y ’ all ride around listening to bounce that shit so ghetto amp give me a headache 😂    
8                                                                        whatever crypto infiltrator u are yeah but ur pro zionist are not u definition of jew believes in and pushes holocaust hoax as well as pushes <number> <number> was done by arabs story    
9                                                                                                                                                                                                              boycottshehnaazkishaadi come on gays make a trend    

  final_label  class  pred_class  correct_pred  
1  hatespeech      2           0         False  
5      normal      0           2         False  
6   offensive      1           0         False  
8  hatespeech      2           1         False  
9      normal      0           1         False

In [59]:
misclass_norm_df = misclass_df[misclass_df['class'] == 0]
misclass_offe_df = misclass_df[misclass_df['class'] == 1]
misclass_hate_df = misclass_df[misclass_df['class'] == 2]

In [62]:
print('Normal Examples Misclassified: ' + str(len(misclass_norm_df)))
print('Offensive Examples Misclassified: ' + str(len(misclass_offe_df)))
print('Hate Examples Misclassified: ' + str(len(misclass_hate_df)))

Normal Examples Misclassified: 129
Offensive Examples Misclassified: 319
Hate Examples Misclassified: 113


In [65]:
misclass_norm_df.head(50)

post_id                                   target1  \
5    1172328099188330497_twitter                                  ['None']   
9    1228700650499784704_twitter                            ['Homosexual']   
38   1179066581944557575_twitter                               ['Refugee']   
74   1178733292524163072_twitter                            ['Homosexual']   
84   1179089265038249984_twitter                                  ['None']   
85   1178513955041501184_twitter                                  ['None']   
100  1170830037878104066_twitter                                 ['Other']   
107                 18360243_gab  ['African', 'Arab', 'Asian', 'Hispanic']   
123  1118721393313579008_twitter                                 ['Other']   
124  1211716604016369665_twitter                                  ['None']   
127                 27604258_gab                                ['Jewish']   
191  1178112963800162304_twitter                                  ['None']   
230  1178649697554194432_twitter                                  ['None']   
235                 22986133_gab                                  ['None']   
245  1178841151580905473_twitter                                  ['None']   
262                 19570873_gab                         ['Arab', 'Islam']   
268                  6045951_gab                                 ['Other']   
283  1139106256008953856_twitter                                 ['Women']   
297  1178428495824859136_twitter                                  ['None']   
313  1179096960537632768_twitter                                  ['None']   
338                 11399512_gab                               ['Refugee']   
349  1178850274359861252_twitter                            ['Homosexual']   
409                  3065094_gab                                 ['Islam']   
413  1092108135962009601_twitter                                  ['None']   
465                  5863477_gab                                  ['None']   
475  1171703732406489088_twitter                                  ['None']   
478  1178633687879077889_twitter                                  ['None']   
490                 20893287_gab                                 ['Other']   
510  1178490118786600966_twitter                                  ['None']   
513                 14018539_gab                                 ['Islam']   
532                 18102033_gab                                 ['Other']   
546  1121949459716292608_twitter                                  ['None']   
565                 14903335_gab                                  ['None']   
580                 23252924_gab                                  ['None']   
593  1190497758517637125_twitter                                 ['Islam']   
612  1179098860792291329_twitter                                 ['Asian']   
628  1261352638274125824_twitter                                  ['None']   
634  1179011774403756032_twitter                            ['Homosexual']   
637  1177933241099194368_twitter                                  ['None']   
652                 10413780_gab                                  ['None']   
674                  4299781_gab                                  ['None']   
678                 17724232_gab                               ['Refugee']   
711                 14540497_gab                               ['Refugee']   
717  1090157360981536769_twitter                                  ['None']   
787  1178828209342861313_twitter                                  ['None']   
798                  6355604_gab                                  ['None']   
800                  9274864_gab                                  ['None']   
804  1178808989552787457_twitter                                  ['None']   
814  1185669351241912320_twitter                                  ['None']   
815                 13912589_gab                            ['Homosexual']   

              target2                        t

In [66]:
misclass_offe_df.head(50)

post_id                      target1  \
6    1278566981466296320_twitter                     ['None']   
11                  25213655_gab                    ['Islam']   
12   1201089995102015490_twitter                    ['Islam']   
19                  24941415_gab                    ['Women']   
20   1177583026730983424_twitter                  ['African']   
35                   7456053_gab                     ['None']   
39   1178062774834012161_twitter               ['Homosexual']   
40   1174368692483833857_twitter                    ['Women']   
45   1094696319321550851_twitter                  ['African']   
49                  17561056_gab                     ['None']   
51                   9727340_gab                     ['None']   
55   1178702576726024193_twitter                    ['Women']   
75   1178971709975728128_twitter                     ['None']   
76                   6379567_gab                    ['Other']   
79                  14573670_gab                  ['African']   
87                  20771302_gab  ['African', 'Men', 'Women']   
88   1080578011047571473_twitter                  ['Refugee']   
94                  21056476_gab     ['Jewish', 'Homosexual']   
101  1179052072412557312_twitter               ['Homosexual']   
106  1263316123019345925_twitter               ['Homosexual']   
108                  4234170_gab                  ['African']   
111  1207723806950866951_twitter                    ['Other']   
117  1215555285571342337_twitter                    ['Islam']   
131                 12089686_gab                    ['Other']   
136                 17503871_gab                     ['None']   
141                  9011747_gab                  ['African']   
150                  9120350_gab       ['Women', 'Caucasian']   
161                 12171519_gab                     ['Arab']   
162  1079383410366271488_twitter                    ['Women']   
164  1201151324219494401_twitter                     ['None']   
165                  9723726_gab                   ['Jewish']   
166                  3145758_gab                    ['Islam']   
167                 22679682_gab                  ['African']   
174  1076286149310730240_twitter         ['African', 'Women']   
176                 19941799_gab                    ['Asian']   
187                 27715195_gab                 ['Hispanic']   
189                  8711615_gab                  ['African']   
192  1178750430219780098_twitter                     ['None']   
203  1179046168044736512_twitter                    ['Other']   
204                 22538599_gab    ['African', 'Homosexual']   
206                  9990225_gab                  ['African']   
214                 13155723_gab                   ['Jewish']   
216                 11983952_gab                     ['None']   
217                  2801215_gab         ['Islam', 'Refugee']   
218                  6824264_gab                     ['Arab']   
219                 12661692_gab               ['Homosexual']   
220  1083042797995941889_twitter                    ['Women']   
224  1178034572531044352_twitter               ['Homosexual']   
225  1270768582222385152_twitter                    ['Women']   
232                 13443012_gab       ['Caucasian', 'Women']   

                                                  target2  \
6                                               ['Other']   
11                                              ['Islam']   
12                                              ['Islam']   
19                                              ['Women']   
20                                            ['African']   
35                                               ['Arab']   
39                                         ['Homosexual']   
40                                               ['None']   
45                                            ['African']   
49                                               ['None']   
51                                    

In [67]:
misclass_hate_df.head(50)

post_id  \
1                    4376210_gab   
8                    6070354_gab   
16                  20104013_gab   
25                  13855748_gab   
34   1268038905137369088_twitter   
50                  24017670_gab   
52   1179046002503929857_twitter   
71                  26985222_gab   
77   1252162171603124225_twitter   
115  1177951117780504576_twitter   
118  1177927419740770304_twitter   
138  1177597442662879234_twitter   
148                  5125277_gab   
158                 12802903_gab   
183  1116531316508495872_twitter   
246                 27265236_gab   
259  1229209066276315138_twitter   
266                 22065104_gab   
267                 10562250_gab   
280                 20188913_gab   
282                 27618184_gab   
299  1178771601824915456_twitter   
304                 11103370_gab   
312                 11163076_gab   
389  1143683682869436416_twitter   
395                  9167222_gab   
402  1179058422421041152_twitter   
403  1092620747015680000_twitter   
411                 25649190_gab   
414                 12197351_gab   
422                 12764956_gab   
425  1178696300251926530_twitter   
435                 26989362_gab   
452                 16473812_gab   
462                 16337650_gab   
469  1178727064397987840_twitter   
473  1178915039924895744_twitter   
492                 20063210_gab   
528                 11412734_gab   
556  1178110624905224192_twitter   
560  1178631491783397376_twitter   
568                 27381805_gab   
664                 12211234_gab   
706  1178863549692743683_twitter   
713                 21649243_gab   
736  1179323434066743296_twitter   
738                  1738721_gab   
744                 15466310_gab   
755                 15198461_gab   
779                 16000365_gab   

                                          target1  \
1                                      ['Jewish']   
8                                      ['Jewish']   
16                                      ['Islam']   
25                                    ['African']   
34                                       ['None']   
50                   ['Arab', 'Islam', 'Refugee']   
52                                      ['Asian']   
71                        ['Homosexual', 'Women']   
77                                    ['Refugee']   
115                                ['Homosexual']   
118                                ['Homosexual']   
138                                    ['Indian']   
148                                   ['African']   
158                      ['African', 'Caucasian']   
183                             ['Arab', 'Islam']   
246                                ['Homosexual']   
259                                      ['None']   
266                          ['Islam', 'Refugee']   
267                                ['Homosexual']   
280                      ['African', 'Caucasian']   
282                                   ['Refugee']   
299                     ['African', 'Homosexual']   
304                 ['Other', 'African', 'Women']   
312                                ['Homosexual']   
389                              ['Men', 'Women']   
395                                     ['Islam']   
402                                    ['Jewish']   
403                                      ['None']   
411                                ['Homosexual']   
414                             ['Arab', 'Islam']   
422                             ['Arab', 'Islam']   
425                                ['Homosexual']   
435                                    ['Jewish']   
452                                      ['None']   
462                                ['Homosexual']   
469                                     ['Islam']   
473                                ['Homosexual']   
492                                   ['African']   
528  ['Arab', 'Hindu', 'Men', 'Women', 'Refugee']   
556                                ['Homosexual']   
560            